const editorGroups = document.querySelector('#editor-groups');
const errorBox = document.querySelector('#admin-error');
const toast = document.querySelector('#toast');
const saveButton = document.querySelector('#save-button');
const loginForm = document.querySelector('#admin-login');
const editorForm = document.querySelector('#admin-form');
let config; let adminSecret = '';

function setError(message = '') { errorBox.hidden = !message; errorBox.textContent = message; }
function showToast(message) { toast.textContent = message; toast.classList.add('visible'); setTimeout(() => toast.classList.remove('visible'), 4500); }
function escapeHtml(value = '') { return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;'); }
function makeRow(rowData = {}) { const row = document.createElement('div'); row.className = 'editor-row'; row.innerHTML = `<input class="row-label" type="text" maxlength="60" required placeholder="例：vol.13-1" value="${escapeHtml(rowData.label || '')}"><input class="wine-name" type="text" maxlength="180" placeholder="ワイン名" value="${escapeHtml(rowData.wineName || '')}"><input class="importer-name" type="text" maxlength="120" placeholder="インポーター名" value="${escapeHtml(rowData.importerName || '')}"><button class="icon-button delete-row" type="button" aria-label="項目を削除">×</button>`; row.querySelector('.delete-row').addEventListener('click', () => row.remove()); return row; }
function makeGroup(group) { const card = document.createElement('section'); card.className = 'card editor-group'; card.innerHTML = `<div class="group-toolbar"><label>Vol.グループ名<input class="group-label" type="text" maxlength="60" required value="${escapeHtml(group.label)}"></label><button class="delete-group secondary-button" type="button">このVol.を削除</button></div><div class="rows"></div><button class="add-row add-button" type="button">＋ 項目を追加</button>`; const rows = card.querySelector('.rows'); group.rows.forEach((row) => rows.append(makeRow(row))); card.querySelector('.add-row').addEventListener('click', () => rows.append(makeRow())); card.querySelector('.delete-group').addEventListener('click', () => card.remove()); return card; }
function render() { document.querySelector('#app-title').value = config.title; document.querySelector('#factor').value = config.smallBottleFactor; document.querySelector('#recorder-names').value = (config.recorderNames || []).join('\n'); editorGroups.replaceChildren(...config.groups.map(makeGroup)); }
function readConfig() { return { title: document.querySelector('#app-title').value.trim(), smallBottleFactor: Number(document.querySelector('#factor').value), recorderNames: document.querySelector('#recorder-names').value.split('\n').map((name) => name.trim()).filter(Boolean), groups: [...editorGroups.querySelectorAll('.editor-group')].map((card) => ({ label: card.querySelector('.group-label').value.trim(), rows: [...card.querySelectorAll('.editor-row')].map((row) => ({ label: row.querySelector('.row-label').value.trim(), wineName: row.querySelector('.wine-name').value.trim(), importerName: row.querySelector('.importer-name').value.trim() })) })) }; }
async function loadConfig() { const response = await fetch('/api/config', { cache: 'no-store' }); if (!response.ok) throw new Error('設定を読み込めませんでした。'); config = await response.json(); render(); }

loginForm.addEventListener('submit', async (event) => { event.preventDefault(); setError(); const password = document.querySelector('#admin-key').value; if (!password) return setError('編集用パスワードを入力してください。'); const button = loginForm.querySelector('button'); button.disabled = true; try { const response = await fetch('/api/admin-login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'ログインできませんでした。'); adminSecret = password; await loadConfig(); loginForm.hidden = true; editorForm.hidden = false; } catch (error) { setError(error.message || 'ログインできませんでした。'); } finally { button.disabled = false; } });
document.querySelector('#add-group').addEventListener('click', () => { const nextVolume = editorGroups.children.length + 1; editorGroups.append(makeGroup({ label: `vol.${nextVolume}`, rows: Array.from({ length: 4 }, (_, index) => ({ label: `vol.${nextVolume}-${index + 1}`, wineName: '', importerName: '' })) })); });
editorForm.addEventListener('submit', async (event) => { event.preventDefault(); setError(); saveButton.disabled = true; saveButton.querySelector('.button-label').textContent = '保存中…'; try { const response = await fetch('/api/config', { method: 'PUT', headers: { 'Content-Type': 'application/json', 'X-Admin-Key': adminSecret }, body: JSON.stringify(readConfig()) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || '設定を保存できませんでした。'); config = result; render(); showToast('設定を保存しました。全員の入力画面に反映されます。'); } catch (error) { setError(error.message || '設定を保存できませんでした。'); } finally { saveButton.disabled = false; saveButton.querySelector('.button-label').textContent = '変更を保存して全員に反映'; } });
