const bottlingForm = document.querySelector('#bottling-form');
const incomingForm = document.querySelector('#incoming-form');
const groups = document.querySelector('#volume-groups');
const incomingGroups = document.querySelector('#incoming-volume-groups');
const dateInput = document.querySelector('#record-date');
const incomingDateInput = document.querySelector('#incoming-date');
const errorBox = document.querySelector('#form-error');
const dialog = document.querySelector('#confirm-dialog');
const preview = document.querySelector('#report-preview');
const confirmButton = document.querySelector('#confirm-button');
const toast = document.querySelector('#toast');
const bottlingTab = document.querySelector('#bottling-tab');
const incomingTab = document.querySelector('#incoming-tab');
const deleteDialog = document.querySelector('#delete-dialog');
let appConfig; let pendingReport; let pendingDelete;

function formatNumber(value) { return new Intl.NumberFormat('ja-JP', { maximumFractionDigits: 2 }).format(value); }
function escapeHtml(value = '') { return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;'); }
function today() { return new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Tokyo' }); }
function setError(message = '') { errorBox.hidden = !message; errorBox.textContent = message; }
function showToast(message) { toast.textContent = message; toast.classList.add('visible'); window.setTimeout(() => toast.classList.remove('visible'), 5500); }
function rowById(id) { return appConfig.groups.flatMap((group) => group.rows).find((row) => row.id === id); }
function populateRecorderOptions() { const names = Array.isArray(appConfig.recorderNames) ? appConfig.recorderNames : []; ['#bottling-recorder', '#incoming-recorder'].forEach((selector) => { const select = document.querySelector(selector); select.replaceChildren(new Option('選択してください', ''), ...names.map((name) => new Option(name, name))); }); }

function makeGroups(target, prefix, kind) {
  target.replaceChildren();
  appConfig.groups.forEach((group, groupIndex) => {
    const detail = document.createElement('details'); detail.open = groupIndex === 0;
    detail.innerHTML = `<summary>${escapeHtml(group.label)}</summary><div class="volume-inputs">${group.rows.map((row) => `<div class="wine-input ${kind === 'incoming' ? 'incoming-wine-input' : ''}"><label for="${prefix}${escapeHtml(row.id)}"><span>${escapeHtml(row.label)}</span><small>${escapeHtml(row.wineName || 'ワイン名未設定')}${kind === 'incoming' ? `<em>${escapeHtml(row.importerName || 'インポーター未設定')}</em>` : ''}</small></label><input id="${prefix}${escapeHtml(row.id)}" name="${escapeHtml(row.id)}" type="number" inputmode="numeric" min="0" max="9999" step="1" placeholder="0" aria-label="${escapeHtml(row.label)}の${kind === 'incoming' ? '入荷' : '使用'}本数" />${kind === 'incoming' ? `<label class="item-note-field" for="note-${prefix}${escapeHtml(row.id)}"><span>銘柄別備考（任意）</span><textarea id="note-${prefix}${escapeHtml(row.id)}" data-item-note="${escapeHtml(row.id)}" rows="2" maxlength="1000"></textarea></label>` : ''}</div>`).join('')}</div>`;
    target.append(detail);
  });
}
function createInputs() { makeGroups(groups, 'b-', 'bottling'); makeGroups(incomingGroups, 'i-', 'incoming'); }
function itemsFrom(target) { const notes = new Map([...target.querySelectorAll('[data-item-note]')].map((input) => [input.dataset.itemNote, input.value.trim()])); return [...target.querySelectorAll('input[type="number"]')].map((input) => ({ id: input.name, bottles: Number(input.value || 0) })).filter((item) => Number.isInteger(item.bottles) && item.bottles > 0).map((item) => ({ ...item, ...rowById(item.id), itemNote: notes.get(item.id) || '', smallBottles: item.bottles * appConfig.smallBottleFactor })); }
function getBottlingReport() { const items = itemsFrom(groups); const total = items.reduce((sum, item) => sum + item.bottles, 0); return { type: 'bottling', date: dateInput.value, recorderName: document.querySelector('#bottling-recorder').value.trim(), notes: document.querySelector('#bottling-notes').value.trim(), items, totalBottles: total, totalSmallBottles: total * appConfig.smallBottleFactor }; }
function getIncomingReport() { const items = itemsFrom(incomingGroups); return { type: 'incoming', date: incomingDateInput.value, recorderName: document.querySelector('#incoming-recorder').value.trim(), supplier: document.querySelector('#incoming-supplier').value.trim(), notes: document.querySelector('#incoming-notes').value.trim(), items, totalBottles: items.reduce((sum, item) => sum + item.bottles, 0) }; }
function updateSummary() { const r = getBottlingReport(); document.querySelector('#total-bottles').textContent = formatNumber(r.totalBottles); document.querySelector('#total-small-bottles').textContent = formatNumber(r.totalSmallBottles); }
function updateIncomingSummary() { const r = getIncomingReport(); document.querySelector('#incoming-total-bottles').textContent = formatNumber(r.totalBottles); document.querySelector('#incoming-total-wines').textContent = formatNumber(r.items.length); }
function reportText(r) { const lines = r.items.map((item) => r.type === 'incoming' ? `・${item.label}｜${item.wineName}: ${formatNumber(item.bottles)}本${item.itemNote ? `\n  銘柄別備考: ${item.itemNote}` : ''}` : `・${item.label}｜${item.wineName}: ${formatNumber(item.bottles)}本 → 小瓶 ${formatNumber(item.smallBottles)}本`).join('\n'); const itemSummary = lines || '・本数入力なし（備考のみの記録）'; return r.type === 'incoming' ? `入荷記録\n記入日: ${r.date}\n記入者: ${r.recorderName}\n\n入荷ワイン\n${itemSummary}\n\n合計: ${formatNumber(r.totalBottles)}本${r.supplier ? `\n仕入先: ${r.supplier}` : ''}${r.notes ? `\n\n備考\n${r.notes}` : ''}` : `瓶詰め記録\n作業日: ${r.date}\n記入者: ${r.recorderName}\n\n使用ワイン\n${itemSummary}\n\n合計: 使用 ${formatNumber(r.totalBottles)}本 / 小瓶 ${formatNumber(r.totalSmallBottles)}本${r.notes ? `\n\n備考\n${r.notes}` : ''}`; }
function switchMode(mode) { const bottling = mode === 'bottling'; bottlingForm.hidden = !bottling; incomingForm.hidden = bottling; bottlingTab.classList.toggle('active', bottling); incomingTab.classList.toggle('active', !bottling); bottlingTab.setAttribute('aria-selected', String(bottling)); incomingTab.setAttribute('aria-selected', String(!bottling)); setError(); }
function openConfirm(r) { setError(); if (!r.date) return setError(r.type === 'incoming' ? '記入日を入力してください。' : '作業日を入力してください。'); if (!r.recorderName) return setError('記入者名を入力してください。'); if (!r.items.length && (r.type === 'incoming' || !r.notes)) return setError(r.type === 'incoming' ? '入荷したワインと本数を入力してください。' : '使用本数または備考を入力してください。'); pendingReport = r; preview.textContent = reportText(r); dialog.showModal(); }
function formatHistory(item, type) { const date = String(item.date || '').replaceAll('-', '/'); const notesOnly = type === 'bottling' && !item.program && !item.wineName && Number(item.bottles) === 0; const notes = [item.itemNote ? `銘柄別備考：${escapeHtml(item.itemNote)}` : '', item.notes ? `備考：${escapeHtml(item.notes)}` : ''].filter(Boolean).map((note) => `<p>${note}</p>`).join(''); const sub = notesOnly ? '本数入力なし' : type === 'incoming' ? `入荷 ${formatNumber(item.bottles)}本${item.supplier ? ` ／ ${escapeHtml(item.supplier)}` : ''}` : `使用 ${formatNumber(item.bottles)}本 → 小瓶 ${formatNumber(item.smallBottles)}本`; const program = notesOnly ? '備考のみの記録' : item.program; const wineName = notesOnly ? '' : item.wineName; const label = notesOnly ? '備考のみの記録' : `${item.program}｜${item.wineName}`; return `<article class="history-item"><div><strong>${escapeHtml(program)}</strong><span>${escapeHtml(wineName)}</span></div><div class="history-meta"><span>${date} ・ ${escapeHtml(item.recorderName || '記入者未入力')}</span><b>${sub}</b></div>${notes}<button class="history-delete" type="button" data-history="${type}" data-row-number="${Number(item.rowNumber)}" data-label="${escapeHtml(label)}">削除</button></article>`; }
async function loadHistory(type) { const panel = document.querySelector(`#${type}-history`); panel.innerHTML = '<p class="history-empty">履歴を読み込み中です。</p>'; try { const response = await fetch(`/api/history?type=${type}`, { cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error); panel.innerHTML = result.items.length ? result.items.map((item) => formatHistory(item, type)).join('') : '<p class="history-empty">直近2日間の記録はありません。</p>'; } catch (error) { panel.innerHTML = '<p class="history-empty">履歴を読み込めませんでした。更新してください。</p>'; } }

bottlingForm.addEventListener('input', updateSummary); incomingForm.addEventListener('input', updateIncomingSummary);
bottlingForm.addEventListener('submit', (event) => { event.preventDefault(); openConfirm(getBottlingReport()); }); incomingForm.addEventListener('submit', (event) => { event.preventDefault(); openConfirm(getIncomingReport()); });
bottlingTab.addEventListener('click', () => switchMode('bottling')); incomingTab.addEventListener('click', () => switchMode('incoming')); document.querySelector('#back-button').addEventListener('click', () => dialog.close());
document.querySelectorAll('.history-refresh').forEach((button) => button.addEventListener('click', () => loadHistory(button.dataset.history)));
document.addEventListener('click', (event) => { const button = event.target.closest('.history-delete'); if (!button) return; pendingDelete = { type: button.dataset.history, rowNumber: Number(button.dataset.rowNumber) }; document.querySelector('#delete-preview').textContent = button.dataset.label; deleteDialog.showModal(); });
document.querySelector('#delete-cancel').addEventListener('click', () => deleteDialog.close());
document.querySelector('#delete-confirm').addEventListener('click', async () => { if (!pendingDelete) return; const button = document.querySelector('#delete-confirm'); button.disabled = true; button.textContent = '削除中…'; try { const response = await fetch(`/api/history?type=${pendingDelete.type}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rowNumber: pendingDelete.rowNumber }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || '履歴を削除できませんでした。'); deleteDialog.close(); loadHistory(pendingDelete.type); showToast('履歴を削除しました。'); pendingDelete = null; } catch (error) { showToast(error.message || '履歴を削除できませんでした。'); } finally { button.disabled = false; button.textContent = '削除する'; } });
confirmButton.addEventListener('click', async () => { if (!pendingReport) return; confirmButton.disabled = true; confirmButton.textContent = '送信中…'; try { const payload = { ...pendingReport, items: pendingReport.items.map(({ id, bottles, itemNote }) => ({ id, bottles, itemNote })) }; const response = await fetch('/api/report', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!result.sheetsSaved) throw new Error(result.error || '記録の送信に失敗しました。'); const savedType = pendingReport.type; dialog.close(); if (savedType === 'incoming') { incomingForm.reset(); incomingDateInput.value = today(); updateIncomingSummary(); } else { bottlingForm.reset(); dateInput.value = today(); updateSummary(); } showToast(result.ok ? 'Slackと在庫管理シートへ記録しました。' : result.error); pendingReport = null; loadHistory(savedType); } catch (error) { setError(error.message || '記録の送信に失敗しました。'); dialog.close(); window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' }); } finally { confirmButton.disabled = false; confirmButton.textContent = '記録を送信する'; } });
fetch('/api/config', { cache: 'no-store' }).then((response) => { if (!response.ok) throw new Error('設定を取得できませんでした。'); return response.json(); }).then((config) => { appConfig = config; document.title = config.title; document.querySelector('#page-title').textContent = config.title; document.querySelector('.multiplier').textContent = `1本 = 小瓶 ${formatNumber(config.smallBottleFactor)}本`; populateRecorderOptions(); createInputs(); dateInput.value = today(); incomingDateInput.value = today(); updateSummary(); updateIncomingSummary(); loadHistory('bottling'); loadHistory('incoming'); }).catch((error) => setError(error.message || '設定を取得できませんでした。'));
