const forms = { bottling: document.querySelector('#bottling-form'), incoming: document.querySelector('#incoming-form'), shipping: document.querySelector('#shipping-form') };
const tabs = { bottling: document.querySelector('#bottling-tab'), incoming: document.querySelector('#incoming-tab'), shipping: document.querySelector('#shipping-tab') };
const groupPanels = { bottling: document.querySelector('#volume-groups'), incoming: document.querySelector('#incoming-volume-groups'), shipping: document.querySelector('#shipping-volume-groups') };
const dateInputs = { bottling: document.querySelector('#record-date'), incoming: document.querySelector('#incoming-date'), shipping: document.querySelector('#shipping-date') };
const errorBox = document.querySelector('#form-error');
const dialog = document.querySelector('#confirm-dialog');
const preview = document.querySelector('#report-preview');
const confirmButton = document.querySelector('#confirm-button');
const toast = document.querySelector('#toast');
const deleteDialog = document.querySelector('#delete-dialog');
let appConfig; let pendingReport; let pendingDelete;

function formatNumber(value) { return new Intl.NumberFormat('ja-JP', { maximumFractionDigits: 2 }).format(value); }
function escapeHtml(value = '') { return String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;'); }
function today() { return new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Tokyo' }); }
function setError(message = '') { errorBox.hidden = !message; errorBox.textContent = message; }
function showToast(message) { toast.textContent = message; toast.classList.add('visible'); window.setTimeout(() => toast.classList.remove('visible'), 5500); }
function rowById(id) { return appConfig.groups.flatMap((group) => group.rows).find((row) => row.id === id); }
function isShippingProgram(label = '') { const match = String(label).match(/^vol\.(\d+)(?:-|$)/i); return Boolean(match && Number(match[1]) >= 1 && Number(match[1]) <= 12); }
function shippingGroups() { return appConfig.groups.map((group) => ({ ...group, rows: group.rows.filter((row) => isShippingProgram(row.label)) })).filter((group) => group.rows.length); }
function populateRecorderOptions() { const names = Array.isArray(appConfig.recorderNames) ? appConfig.recorderNames : []; ['#bottling-recorder', '#incoming-recorder', '#shipping-recorder'].forEach((selector) => { const select = document.querySelector(selector); select.replaceChildren(new Option('選択してください', ''), ...names.map((name) => new Option(name, name))); }); }

function makeGroups(target, prefix, kind, sourceGroups = appConfig.groups) {
  target.replaceChildren();
  sourceGroups.forEach((group, groupIndex) => {
    const detail = document.createElement('details'); detail.open = groupIndex === 0;
    const isIncoming = kind === 'incoming'; const action = isIncoming ? '入荷' : kind === 'shipping' ? '出荷' : '使用';
    detail.innerHTML = `<summary>${escapeHtml(group.label)}</summary><div class="volume-inputs">${group.rows.map((row) => `<div class="wine-input ${isIncoming ? 'incoming-wine-input' : ''}"><label for="${prefix}${escapeHtml(row.id)}"><span>${escapeHtml(row.label)}</span><small>${escapeHtml(row.wineName || 'ワイン名未設定')}${isIncoming ? `<em>${escapeHtml(row.importerName || 'インポーター未設定')}</em>` : ''}</small></label><input id="${prefix}${escapeHtml(row.id)}" name="${escapeHtml(row.id)}" type="number" inputmode="numeric" min="0" max="9999" step="1" placeholder="0" aria-label="${escapeHtml(row.label)}の${action}本数" />${isIncoming ? `<label class="item-note-field" for="note-${prefix}${escapeHtml(row.id)}"><span>銘柄別備考（任意）</span><textarea id="note-${prefix}${escapeHtml(row.id)}" data-item-note="${escapeHtml(row.id)}" rows="2" maxlength="1000"></textarea></label>` : ''}</div>`).join('')}</div>`;
    target.append(detail);
  });
}
function createInputs() { makeGroups(groupPanels.bottling, 'b-', 'bottling'); makeGroups(groupPanels.incoming, 'i-', 'incoming'); makeGroups(groupPanels.shipping, 's-', 'shipping', shippingGroups()); }
function itemsFrom(target) { const notes = new Map([...target.querySelectorAll('[data-item-note]')].map((input) => [input.dataset.itemNote, input.value.trim()])); return [...target.querySelectorAll('input[type="number"]')].map((input) => ({ id: input.name, bottles: Number(input.value || 0) })).filter((item) => Number.isInteger(item.bottles) && item.bottles > 0).map((item) => ({ ...item, ...rowById(item.id), itemNote: notes.get(item.id) || '', smallBottles: item.bottles * appConfig.smallBottleFactor })); }
function getReport(type) { const items = itemsFrom(groupPanels[type]); const total = items.reduce((sum, item) => sum + item.bottles, 0); return { type, date: dateInputs[type].value, recorderName: document.querySelector(`#${type}-recorder`).value.trim(), notes: document.querySelector(`#${type}-notes`).value.trim(), supplier: type === 'incoming' ? document.querySelector('#incoming-supplier').value.trim() : '', items, totalBottles: total, totalSmallBottles: type === 'bottling' ? total * appConfig.smallBottleFactor : 0 }; }
function updateSummary(type) { const report = getReport(type); if (type === 'bottling') { document.querySelector('#total-bottles').textContent = formatNumber(report.totalBottles); document.querySelector('#total-small-bottles').textContent = formatNumber(report.totalSmallBottles); return; } document.querySelector(`#${type}-total-bottles`).textContent = formatNumber(report.totalBottles); document.querySelector(`#${type}-total-wines`).textContent = formatNumber(report.items.length); }

function reportText(report) {
  const lines = report.items.map((item) => report.type === 'incoming' ? `・${item.label}｜${item.wineName}: ${formatNumber(item.bottles)}本${item.itemNote ? `\n  銘柄別備考: ${item.itemNote}` : ''}` : report.type === 'shipping' ? `・${item.label}｜${item.wineName}: ${formatNumber(item.bottles)}本` : `・${item.label}｜${item.wineName}: ${formatNumber(item.bottles)}本 → 小瓶 ${formatNumber(item.smallBottles)}本`).join('\n');
  const itemSummary = lines || '・本数入力なし（備考のみの記録）';
  if (report.type === 'incoming') return `入荷記録\n記入日: ${report.date}\n記入者: ${report.recorderName}\n\n入荷ワイン\n${itemSummary}\n\n合計: ${formatNumber(report.totalBottles)}本${report.supplier ? `\n仕入先: ${report.supplier}` : ''}${report.notes ? `\n\n備考\n${report.notes}` : ''}`;
  if (report.type === 'shipping') return `ボトル販売出荷記録\n出荷日: ${report.date}\n記入者: ${report.recorderName}\n\n出荷ワイン\n${itemSummary}\n\n合計: ${formatNumber(report.totalBottles)}本${report.notes ? `\n\n備考\n${report.notes}` : ''}`;
  return `瓶詰め記録\n作業日: ${report.date}\n記入者: ${report.recorderName}\n\n使用ワイン\n${itemSummary}\n\n合計: 使用 ${formatNumber(report.totalBottles)}本 / 小瓶 ${formatNumber(report.totalSmallBottles)}本${report.notes ? `\n\n備考\n${report.notes}` : ''}`;
}
function switchMode(mode) { Object.keys(forms).forEach((type) => { const active = type === mode; forms[type].hidden = !active; tabs[type].classList.toggle('active', active); tabs[type].setAttribute('aria-selected', String(active)); }); setError(); }
function openConfirm(report) { setError(); if (!report.date) return setError(report.type === 'shipping' ? '出荷日を入力してください。' : report.type === 'incoming' ? '記入日を入力してください。' : '作業日を入力してください。'); if (!report.recorderName) return setError('記入者名を入力してください。'); if (!report.items.length && (report.type !== 'bottling' || !report.notes)) return setError(report.type === 'shipping' ? '出荷したワインと本数を入力してください。' : report.type === 'incoming' ? '入荷したワインと本数を入力してください。' : '使用本数または備考を入力してください。'); pendingReport = report; preview.textContent = reportText(report); dialog.showModal(); }
function formatHistory(item, type) { const date = String(item.date || '').replaceAll('-', '/'); const notesOnly = type === 'bottling' && !item.program && !item.wineName && Number(item.bottles) === 0; const notes = [item.itemNote ? `銘柄別備考：${escapeHtml(item.itemNote)}` : '', item.notes ? `備考：${escapeHtml(item.notes)}` : ''].filter(Boolean).map((note) => `<p>${note}</p>`).join(''); const sub = notesOnly ? '本数入力なし' : type === 'incoming' ? `入荷 ${formatNumber(item.bottles)}本${item.supplier ? ` ／ ${escapeHtml(item.supplier)}` : ''}` : type === 'shipping' ? `出荷 ${formatNumber(item.bottles)}本` : `使用 ${formatNumber(item.bottles)}本 → 小瓶 ${formatNumber(item.smallBottles)}本`; const program = notesOnly ? '備考のみの記録' : item.program; const wineName = notesOnly ? '' : item.wineName; const label = notesOnly ? '備考のみの記録' : `${item.program}｜${item.wineName}`; return `<article class="history-item"><div><strong>${escapeHtml(program)}</strong><span>${escapeHtml(wineName)}</span></div><div class="history-meta"><span>${date} ・ ${escapeHtml(item.recorderName || '記入者未入力')}</span><b>${sub}</b></div>${notes}<button class="history-delete" type="button" data-history="${type}" data-row-number="${Number(item.rowNumber)}" data-label="${escapeHtml(label)}">削除</button></article>`; }
async function loadHistory(type) { const panel = document.querySelector(`#${type}-history`); panel.innerHTML = '<p class="history-empty">履歴を読み込み中です。</p>'; try { const response = await fetch(`/api/history?type=${type}`, { cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error); panel.innerHTML = result.items.length ? result.items.map((item) => formatHistory(item, type)).join('') : '<p class="history-empty">直近2日間の記録はありません。</p>'; } catch (error) { panel.innerHTML = '<p class="history-empty">履歴を読み込めませんでした。更新してください。</p>'; } }

Object.keys(forms).forEach((type) => { forms[type].addEventListener('input', () => updateSummary(type)); forms[type].addEventListener('submit', (event) => { event.preventDefault(); openConfirm(getReport(type)); }); tabs[type].addEventListener('click', () => switchMode(type)); });
document.querySelector('#back-button').addEventListener('click', () => dialog.close());
document.querySelectorAll('.history-refresh').forEach((button) => button.addEventListener('click', () => loadHistory(button.dataset.history)));
document.addEventListener('click', (event) => { const button = event.target.closest('.history-delete'); if (!button) return; pendingDelete = { type: button.dataset.history, rowNumber: Number(button.dataset.rowNumber) }; document.querySelector('#delete-preview').textContent = button.dataset.label; deleteDialog.showModal(); });
document.querySelector('#delete-cancel').addEventListener('click', () => deleteDialog.close());
document.querySelector('#delete-confirm').addEventListener('click', async () => { if (!pendingDelete) return; const button = document.querySelector('#delete-confirm'); button.disabled = true; button.textContent = '削除中…'; try { const response = await fetch(`/api/history?type=${pendingDelete.type}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ rowNumber: pendingDelete.rowNumber }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || '履歴を削除できませんでした。'); deleteDialog.close(); loadHistory(pendingDelete.type); showToast('履歴を削除しました。'); pendingDelete = null; } catch (error) { showToast(error.message || '履歴を削除できませんでした。'); } finally { button.disabled = false; button.textContent = '削除する'; } });
confirmButton.addEventListener('click', async () => { if (!pendingReport) return; confirmButton.disabled = true; confirmButton.textContent = '送信中…'; try { const payload = { ...pendingReport, items: pendingReport.items.map(({ id, bottles, itemNote }) => ({ id, bottles, itemNote })) }; const response = await fetch('/api/report', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!result.sheetsSaved) throw new Error(result.error || '記録の送信に失敗しました。'); const savedType = pendingReport.type; dialog.close(); forms[savedType].reset(); dateInputs[savedType].value = today(); updateSummary(savedType); showToast(result.ok ? 'Slackと在庫管理シートへ記録しました。' : result.error); pendingReport = null; loadHistory(savedType); } catch (error) { setError(error.message || '記録の送信に失敗しました。'); dialog.close(); window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' }); } finally { confirmButton.disabled = false; confirmButton.textContent = '記録を送信する'; } });
fetch('/api/config', { cache: 'no-store' }).then((response) => { if (!response.ok) throw new Error('設定を取得できませんでした。'); return response.json(); }).then((config) => { appConfig = config; document.title = `${config.title}・入荷・出荷`; document.querySelector('#page-title').textContent = `${config.title}・入荷・出荷`; document.querySelector('.multiplier').textContent = `1本 = 小瓶 ${formatNumber(config.smallBottleFactor)}本`; populateRecorderOptions(); createInputs(); Object.keys(dateInputs).forEach((type) => { dateInputs[type].value = today(); updateSummary(type); loadHistory(type); }); }).catch((error) => setError(error.message || '設定を取得できませんでした。'));
